name: ShellMate Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6  # Replace with the desired Python version


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: ShellMate Publish
      env:
        TWINE_USERNAME: ZeroAndOne



        TWINE_PASSWORD: KUW4ksA6s9JmPWp

      run: |
        python -m pip install --upgrade twine
        twine upload dist/*
